name: Standard workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
          uses: actions/checkout@v2
          run: yarn install

      - name: Lint
          run: yarn lint

      - name: Build
          run: yarn build

      - name: Deploy to GH pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: build
            CLEAN: true
